### ISSUE TITLE
UnsupportedClassVersionError on JRE 8

### ISSUE THREAD

**Issue by emanueloliveira23** [newrelic/opentelemetry-exporter-java#149]
Hello there! o/

First of all, thank you for the great work here.

I'm using the last version  `0.13.0` and I got the following exception while running on JRE 8:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

Then I downloaded the jar, extract it and check the `.class` version:
```bash
➜  opentelemetry jar xf opentelemetry-exporters-newrelic-0.13.0.jar        
➜  opentelemetry file ./com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.class 
./com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.class: compiled Java class data, version 55.0
```

According to `README.md`, the requirement for the building is `Java 8+`.

The question is: is `opentelemerty-exporter-java` supporting JRE 8?

My `java -version` is:
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by jasonjkeller** [comment]
@emanueloliveira23 Thanks for filing this issue! It looks like some changes in a previous PR didn't work quite as intended and caused the published artifacts to be compiled with Java 11 instead of 8: https://github.com/newrelic/opentelemetry-exporter-java/pull/128

We absolutely intend to support Java 8! I'll look into fixing the issue and getting a `0.13.1` point release out that is compatible with Java 8.

Out of curiosity, how are you utilizing the exporter? Are you just doing manual instrumentation with OTel or using the exporter in conjunction with the OTel Java agent?

**Comment by emanueloliveira23** [comment]
No problem, @jasonjkeller. I noticed that issue and suspected it :D 

About the fix, It's good to know that. Thank you.

Yeah, we're writing our own agent, that is, doing manual instrumentation.

**Comment by jasonjkeller** [comment]
@emanueloliveira23 Here's a new release which should support JRE 8: https://github.com/newrelic/opentelemetry-exporter-java/releases/tag/v0.13.1

If you encounter any further issues just let us know. Thanks again!

**Comment by emanueloliveira23** [comment]
Double thank you, @jasonjkeller 

For sure!
