### ISSUE TITLE
Counters are published with cumulative values

### ISSUE THREAD

**Issue by worekleszczy** [newrelic/opentelemetry-exporter-java#153]
After upgrading from version `0.10.0` to `0.13.1` counters switcher from being reported with deltas to cumulative values. This break rate dashboards in NR and makes NRQL queries like `SELECT sum(counter_name)` yield unexpected values. I noticed that result of this method https://github.com/newrelic/opentelemetry-exporter-java/blob/71127a042034bbf0ad5cbcb30cb05002807a774d/opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapter.java#L57
changed which results in counters not longer being published as deltas.

Similar to #103

**Comment by worekleszczy** [comment]
@jkwatson Can you confirm that this is a bug?

**Comment by jkwatson** [comment]
I don't work at new relic any more. No idea if this is a bug or not.

**Comment by worekleszczy** [comment]
@jasonjkeller @breedx-nr Do you guys know if this is an issue?

**Comment by jasonjkeller** [comment]
@worekleszczy Sorry for the delayed response, totally missed this. This may in fact be a bug. That said, this project is no longer in active development and the project is being archived as is. See https://github.com/newrelic/opentelemetry-exporter-java/issues/155

The reason for this is that New Relic now provides two alternatives for ingesting OTel data that means that there is no longer a need to develop and maintain language specific exporters.

Alternative 1 is to send your data to the OTel collector and configure the collector to send the data to New Relic. Alternative 2 is to send your OTel data directly to a native OTLP ingest endpoint that New Relic provides (this is still early access). Both of these options will allow you to utilize the latest versions of OTel rather than the very outdated version that this exporter supports.

You can learn more about both alternatives here:
* https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start/
* https://docs.newrelic.com/whats-new/2021/04/native-support-opentelemetry/
