### ISSUE TITLE
Should tracerSdk need to cast to tracer? 

### ISSUE THREAD

**Issue by litscher** [newrelic/opentelemetry-exporter-java#20]
I have been following the [README](https://github.com/newrelic/opentelemetry-exporter-java#how-to-use):
<img width="634" alt="image" src="https://user-images.githubusercontent.com/17788855/76083924-b70eb800-5f7c-11ea-9de1-e906222a295d.png">
Should I be casting? Or is there a way to get the opentrace compatible Tracer.

**Comment by jkwatson** [comment]
Hi @litscher . This is more a question for the OpenTelemetry project itself, rather than our exporter. But, if you take a look at this PR:  https://github.com/newrelic/opentelemetry-exporter-java/pull/19/files, I've updated the example to not require casting the Tracer.

One thing to keep in mind: our example here is really mixing two different OpenTelemetry concerns:
1) Instrumentation: this concern can *only* access the classes in the API.
2) Operation/Application Devlopment: this concern is primarily involved with configuring the SDK itself, and thus will need to access the underlying SDK classes.

Usage of an exporter is definitely an example of concern 2, since it is about setting up the SDK to be used in an application. 

If that needs more clarification, I would jump over to the OpenTelemetry gitter channels for more details questions about how to use OpenTelemetry, outside the scope of our exporter.

Hope that helps!
